import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Providers } from "./providers";
// import Script from "next/script";

export const metadata: Metadata = {
  // title: "Catalog w/ Nextjs 16",
  title: {
    template: `%s | Next16 Playground`,
    default: "Next16 Playground",
  },
  description: "Generated by create next app",
};

type Props = Readonly<PropsWithChildren>;

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div id="root">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
