import type { Metadata } from "next";
import "./globals.css";
import { Header, Sidebar } from "@/comps";
import { Providers } from "./providers";
// import Script from "next/script";

export const metadata: Metadata = {
  title: "Catalog w/ Nextjs 16",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body id="root">
        <Providers>
          <header>
            <Header />
          </header>
          <div className="layout">
            <aside>
              <Sidebar />
            </aside>
            <main>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
