import type { Metadata } from "next";
import "./globals.css";
// import "./global-tw.js";
import { Header } from "@/comps/Header";
import { Sidebar } from "@/comps/Sidebar";

export const metadata: Metadata = {
  title: "Catalog w/ Nextjs 16",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="root">
        <header>
          <Header />
        </header>
        <div className="layout">
          <aside>
            <Sidebar />
          </aside>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
