import type { Metadata } from "next";
import "./globals.css";
// import "./global-tw.js";
import { Header } from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Catalog w/ Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-slate-50">
        <header className="sticky top-0 z-50 bg-gray-800 text-white">
          <Header />
        </header>
        <div className="container-fluid flex lg:gap-4 h-full">
          <aside className="w-auto shrink-0">
            <Sidebar />
          </aside>

          <main className="flex-1 py-6">
            <div className="wrapper p-6 rounded bg-white shadow-sm">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
