import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/comps/Header";
import { Sidebar } from "@/comps/Sidebar";
// import Script from "next/script";

export const metadata: Metadata = {
  title: "Catalog w/ Nextjs 16",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body id="root">
        <header>
          <Header />
        </header>
        <div className="layout">
          <aside>
            <Sidebar />
          </aside>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
